version: '3.7'

services:
  py_pass-gen:
    container_name: py_pass-gen
    build: ./docker_django
    image: simple_django:latest
    network_mode: bridge
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - '8000:8000'